// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

/*
Package firestarter is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	GetConfigRequest
	GetConfigListRequest
	SetConfigResponse
	DeleteConfigRequest
	DeleteConfigResponse
	DumpConfigListRequest
	RestoreConfigListRequest
	RestoreConfigListResponse
	Secret
	Config
	ConfigList
	Channels
	GetChannelsRequest
*/
package firestarter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetConfigRequest struct {
	CallbackID string `protobuf:"bytes,1,opt,name=CallbackID" json:"CallbackID,omitempty"`
}

func (m *GetConfigRequest) Reset()                    { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()               {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetConfigRequest) GetCallbackID() string {
	if m != nil {
		return m.CallbackID
	}
	return ""
}

type GetConfigListRequest struct {
}

func (m *GetConfigListRequest) Reset()                    { *m = GetConfigListRequest{} }
func (m *GetConfigListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetConfigListRequest) ProtoMessage()               {}
func (*GetConfigListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SetConfigResponse struct {
}

func (m *SetConfigResponse) Reset()                    { *m = SetConfigResponse{} }
func (m *SetConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*SetConfigResponse) ProtoMessage()               {}
func (*SetConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type DeleteConfigRequest struct {
	CallbackID string `protobuf:"bytes,1,opt,name=CallbackID" json:"CallbackID,omitempty"`
}

func (m *DeleteConfigRequest) Reset()                    { *m = DeleteConfigRequest{} }
func (m *DeleteConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteConfigRequest) ProtoMessage()               {}
func (*DeleteConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteConfigRequest) GetCallbackID() string {
	if m != nil {
		return m.CallbackID
	}
	return ""
}

type DeleteConfigResponse struct {
}

func (m *DeleteConfigResponse) Reset()                    { *m = DeleteConfigResponse{} }
func (m *DeleteConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteConfigResponse) ProtoMessage()               {}
func (*DeleteConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DumpConfigListRequest struct {
	Password string `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
}

func (m *DumpConfigListRequest) Reset()                    { *m = DumpConfigListRequest{} }
func (m *DumpConfigListRequest) String() string            { return proto.CompactTextString(m) }
func (*DumpConfigListRequest) ProtoMessage()               {}
func (*DumpConfigListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DumpConfigListRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RestoreConfigListRequest struct {
	Password   string      `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	ConfigList *ConfigList `protobuf:"bytes,2,opt,name=configList" json:"configList,omitempty"`
}

func (m *RestoreConfigListRequest) Reset()                    { *m = RestoreConfigListRequest{} }
func (m *RestoreConfigListRequest) String() string            { return proto.CompactTextString(m) }
func (*RestoreConfigListRequest) ProtoMessage()               {}
func (*RestoreConfigListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RestoreConfigListRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RestoreConfigListRequest) GetConfigList() *ConfigList {
	if m != nil {
		return m.ConfigList
	}
	return nil
}

type RestoreConfigListResponse struct {
}

func (m *RestoreConfigListResponse) Reset()                    { *m = RestoreConfigListResponse{} }
func (m *RestoreConfigListResponse) String() string            { return proto.CompactTextString(m) }
func (*RestoreConfigListResponse) ProtoMessage()               {}
func (*RestoreConfigListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type Secret struct {
	Key   string `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
}

func (m *Secret) Reset()                    { *m = Secret{} }
func (m *Secret) String() string            { return proto.CompactTextString(m) }
func (*Secret) ProtoMessage()               {}
func (*Secret) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Secret) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Secret) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Config struct {
	Title        string    `protobuf:"bytes,1,opt,name=Title" json:"Title,omitempty"`
	CallbackID   string    `protobuf:"bytes,2,opt,name=CallbackID" json:"CallbackID,omitempty"`
	Channels     []string  `protobuf:"bytes,3,rep,name=Channels" json:"Channels,omitempty"`
	Text         string    `protobuf:"bytes,4,opt,name=Text" json:"Text,omitempty"`
	Regexp       string    `protobuf:"bytes,5,opt,name=Regexp" json:"Regexp,omitempty"`
	URLTemplate  string    `protobuf:"bytes,6,opt,name=URLTemplate" json:"URLTemplate,omitempty"`
	BodyTemplate string    `protobuf:"bytes,7,opt,name=BodyTemplate" json:"BodyTemplate,omitempty"`
	Confirm      bool      `protobuf:"varint,8,opt,name=Confirm" json:"Confirm,omitempty"`
	Actions      []string  `protobuf:"bytes,9,rep,name=Actions" json:"Actions,omitempty"`
	Secrets      []*Secret `protobuf:"bytes,10,rep,name=Secrets" json:"Secrets,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Config) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Config) GetCallbackID() string {
	if m != nil {
		return m.CallbackID
	}
	return ""
}

func (m *Config) GetChannels() []string {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *Config) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Config) GetRegexp() string {
	if m != nil {
		return m.Regexp
	}
	return ""
}

func (m *Config) GetURLTemplate() string {
	if m != nil {
		return m.URLTemplate
	}
	return ""
}

func (m *Config) GetBodyTemplate() string {
	if m != nil {
		return m.BodyTemplate
	}
	return ""
}

func (m *Config) GetConfirm() bool {
	if m != nil {
		return m.Confirm
	}
	return false
}

func (m *Config) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *Config) GetSecrets() []*Secret {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type ConfigList struct {
	Config []*Config `protobuf:"bytes,1,rep,name=config" json:"config,omitempty"`
}

func (m *ConfigList) Reset()                    { *m = ConfigList{} }
func (m *ConfigList) String() string            { return proto.CompactTextString(m) }
func (*ConfigList) ProtoMessage()               {}
func (*ConfigList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ConfigList) GetConfig() []*Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type Channels struct {
	List []string `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *Channels) Reset()                    { *m = Channels{} }
func (m *Channels) String() string            { return proto.CompactTextString(m) }
func (*Channels) ProtoMessage()               {}
func (*Channels) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Channels) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type GetChannelsRequest struct {
}

func (m *GetChannelsRequest) Reset()                    { *m = GetChannelsRequest{} }
func (m *GetChannelsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetChannelsRequest) ProtoMessage()               {}
func (*GetChannelsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func init() {
	proto.RegisterType((*GetConfigRequest)(nil), "firestarter.GetConfigRequest")
	proto.RegisterType((*GetConfigListRequest)(nil), "firestarter.GetConfigListRequest")
	proto.RegisterType((*SetConfigResponse)(nil), "firestarter.SetConfigResponse")
	proto.RegisterType((*DeleteConfigRequest)(nil), "firestarter.DeleteConfigRequest")
	proto.RegisterType((*DeleteConfigResponse)(nil), "firestarter.DeleteConfigResponse")
	proto.RegisterType((*DumpConfigListRequest)(nil), "firestarter.DumpConfigListRequest")
	proto.RegisterType((*RestoreConfigListRequest)(nil), "firestarter.RestoreConfigListRequest")
	proto.RegisterType((*RestoreConfigListResponse)(nil), "firestarter.RestoreConfigListResponse")
	proto.RegisterType((*Secret)(nil), "firestarter.Secret")
	proto.RegisterType((*Config)(nil), "firestarter.Config")
	proto.RegisterType((*ConfigList)(nil), "firestarter.ConfigList")
	proto.RegisterType((*Channels)(nil), "firestarter.Channels")
	proto.RegisterType((*GetChannelsRequest)(nil), "firestarter.GetChannelsRequest")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0x9b, 0xd6, 0x89, 0xc7, 0xa9, 0x54, 0x26, 0x69, 0x59, 0x8c, 0x08, 0xee, 0x9e, 0x22,
	0x21, 0x22, 0x94, 0x0a, 0x21, 0x8e, 0x6d, 0x22, 0x55, 0x88, 0x72, 0x71, 0x52, 0xee, 0xae, 0x3b,
	0x2d, 0x16, 0x8e, 0x6d, 0xbc, 0x1b, 0x68, 0x3f, 0x80, 0xef, 0xe1, 0x17, 0x91, 0xd7, 0x6b, 0xd7,
	0x4e, 0x0d, 0x52, 0x6f, 0x9e, 0x9d, 0xf7, 0xde, 0xec, 0xbc, 0x9d, 0x31, 0x0c, 0x82, 0x24, 0xbe,
	0x09, 0x6f, 0xa7, 0x69, 0x96, 0xc8, 0x04, 0xed, 0x9b, 0x30, 0x23, 0x21, 0xfd, 0x4c, 0x52, 0xc6,
	0x67, 0x70, 0x70, 0x4e, 0x72, 0xae, 0xf2, 0x1e, 0xfd, 0xd8, 0x90, 0x90, 0x38, 0x06, 0x98, 0xfb,
	0x51, 0x74, 0xe5, 0x07, 0xdf, 0x3f, 0x2d, 0x98, 0xe1, 0x1a, 0x13, 0xcb, 0xab, 0x9d, 0xf0, 0x23,
	0x18, 0x55, 0x9c, 0x8b, 0x50, 0x48, 0xcd, 0xe3, 0x43, 0x78, 0xb6, 0x7c, 0xd0, 0x12, 0x69, 0x12,
	0x0b, 0xe2, 0xef, 0x61, 0xb8, 0xa0, 0x88, 0x24, 0x3d, 0xb9, 0x46, 0x93, 0xa6, 0xe5, 0x4e, 0xe0,
	0x70, 0xb1, 0x59, 0xa7, 0x8f, 0x8a, 0xa3, 0x03, 0xfd, 0xd4, 0x17, 0xe2, 0x57, 0x92, 0x5d, 0x6b,
	0xb9, 0x2a, 0xe6, 0x09, 0x30, 0x8f, 0x84, 0x4c, 0x32, 0x7a, 0x12, 0x0f, 0x3f, 0x00, 0x04, 0x15,
	0x81, 0xed, 0xb8, 0xc6, 0xc4, 0x9e, 0x3d, 0x9f, 0xd6, 0xec, 0x9b, 0xd6, 0xf4, 0x6a, 0x50, 0xfe,
	0x12, 0x5e, 0xb4, 0x14, 0xd4, 0x2d, 0xbc, 0x03, 0x73, 0x49, 0x41, 0x46, 0x12, 0x0f, 0xa0, 0xfb,
	0x99, 0xee, 0x75, 0xd9, 0xfc, 0x13, 0x47, 0xb0, 0xf7, 0xd5, 0x8f, 0x36, 0xa4, 0x8a, 0x59, 0x5e,
	0x11, 0xf0, 0x3f, 0x3b, 0x60, 0x16, 0x42, 0x39, 0x60, 0x15, 0xca, 0x88, 0x34, 0xa9, 0x08, 0xb6,
	0xdc, 0xdc, 0xd9, 0x76, 0x33, 0x6f, 0x72, 0xfe, 0xcd, 0x8f, 0x63, 0x8a, 0x04, 0xeb, 0xba, 0xdd,
	0xbc, 0xc9, 0x32, 0x46, 0x84, 0xdd, 0x15, 0xdd, 0x49, 0xb6, 0xab, 0x58, 0xea, 0x1b, 0x8f, 0xc0,
	0xf4, 0xe8, 0x96, 0xee, 0x52, 0xb6, 0xa7, 0x4e, 0x75, 0x84, 0x2e, 0xd8, 0x97, 0xde, 0xc5, 0x8a,
	0xd6, 0x69, 0xe4, 0x4b, 0x62, 0xa6, 0x4a, 0xd6, 0x8f, 0x90, 0xc3, 0xe0, 0x2c, 0xb9, 0xbe, 0xaf,
	0x20, 0x3d, 0x05, 0x69, 0x9c, 0x21, 0x83, 0x9e, 0xea, 0x26, 0x5b, 0xb3, 0xbe, 0x6b, 0x4c, 0xfa,
	0x5e, 0x19, 0xe6, 0x99, 0xd3, 0x40, 0x86, 0x49, 0x2c, 0x98, 0xa5, 0xae, 0x59, 0x86, 0xf8, 0x16,
	0x7a, 0x85, 0x69, 0x82, 0x81, 0xdb, 0x9d, 0xd8, 0xb3, 0x61, 0xe3, 0x1d, 0x8a, 0x9c, 0x57, 0x62,
	0xf8, 0x47, 0x80, 0x07, 0xe7, 0xf1, 0x0d, 0x98, 0xc5, 0xe3, 0x30, 0xa3, 0x85, 0xab, 0x27, 0x4c,
	0x43, 0xf8, 0x18, 0x1a, 0xde, 0x44, 0xf9, 0xd3, 0x1b, 0xea, 0x32, 0xea, 0x9b, 0x8f, 0x00, 0xf3,
	0xe9, 0xd7, 0x10, 0x3d, 0x46, 0xb3, 0xdf, 0x5d, 0xd8, 0x2f, 0x84, 0x96, 0x94, 0xfd, 0x0c, 0x03,
	0xc2, 0x2f, 0xb0, 0xdf, 0xd8, 0x12, 0x3c, 0x6e, 0x54, 0x6d, 0xdb, 0x20, 0xe7, 0x5f, 0xc3, 0xc5,
	0x3b, 0x78, 0x0a, 0x56, 0x45, 0xc1, 0x57, 0xed, 0x52, 0xa5, 0x4c, 0x5b, 0x7f, 0xbc, 0x83, 0x67,
	0x60, 0x55, 0xfb, 0x89, 0x6d, 0x18, 0x67, 0xbc, 0x65, 0xea, 0xf6, 0x32, 0x77, 0xf0, 0x12, 0x06,
	0xf5, 0xbd, 0x44, 0xb7, 0xc1, 0x68, 0xd9, 0x74, 0xe7, 0xf8, 0x3f, 0x88, 0x4a, 0xf6, 0x1c, 0xec,
	0x9a, 0xa9, 0xf8, 0xfa, 0x51, 0x7f, 0x4d, 0xbb, 0x9d, 0xc3, 0xe6, 0xed, 0x75, 0x96, 0x77, 0xae,
	0x4c, 0xf5, 0x8f, 0x3b, 0xf9, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x78, 0x16, 0x8c, 0x7a, 0xf3, 0x04,
	0x00, 0x00,
}
