// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

/*
Package firestarter is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	GetConfigListRequest
	SetConfigResponse
	DeleteConfigRequest
	DeleteConfigResponse
	Config
	ConfigList
	Channels
	GetChannelsRequest
*/
package firestarter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetConfigListRequest struct {
}

func (m *GetConfigListRequest) Reset()                    { *m = GetConfigListRequest{} }
func (m *GetConfigListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetConfigListRequest) ProtoMessage()               {}
func (*GetConfigListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SetConfigResponse struct {
}

func (m *SetConfigResponse) Reset()                    { *m = SetConfigResponse{} }
func (m *SetConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*SetConfigResponse) ProtoMessage()               {}
func (*SetConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type DeleteConfigRequest struct {
	CallbackID string `protobuf:"bytes,1,opt,name=CallbackID,json=callbackID" json:"CallbackID,omitempty"`
}

func (m *DeleteConfigRequest) Reset()                    { *m = DeleteConfigRequest{} }
func (m *DeleteConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteConfigRequest) ProtoMessage()               {}
func (*DeleteConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeleteConfigRequest) GetCallbackID() string {
	if m != nil {
		return m.CallbackID
	}
	return ""
}

type DeleteConfigResponse struct {
}

func (m *DeleteConfigResponse) Reset()                    { *m = DeleteConfigResponse{} }
func (m *DeleteConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteConfigResponse) ProtoMessage()               {}
func (*DeleteConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Config struct {
	Title        string   `protobuf:"bytes,1,opt,name=Title,json=title" json:"Title,omitempty"`
	CallbackID   string   `protobuf:"bytes,2,opt,name=CallbackID,json=callbackID" json:"CallbackID,omitempty"`
	Channels     []string `protobuf:"bytes,3,rep,name=Channels,json=channels" json:"Channels,omitempty"`
	Text         string   `protobuf:"bytes,4,opt,name=Text,json=text" json:"Text,omitempty"`
	Regexp       string   `protobuf:"bytes,5,opt,name=Regexp,json=regexp" json:"Regexp,omitempty"`
	URLTemplate  string   `protobuf:"bytes,6,opt,name=URLTemplate,json=uRLTemplate" json:"URLTemplate,omitempty"`
	BodyTemplate string   `protobuf:"bytes,7,opt,name=BodyTemplate,json=bodyTemplate" json:"BodyTemplate,omitempty"`
	Confirm      bool     `protobuf:"varint,8,opt,name=Confirm,json=confirm" json:"Confirm,omitempty"`
	Actions      []string `protobuf:"bytes,9,rep,name=Actions,json=actions" json:"Actions,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Config) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Config) GetCallbackID() string {
	if m != nil {
		return m.CallbackID
	}
	return ""
}

func (m *Config) GetChannels() []string {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *Config) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Config) GetRegexp() string {
	if m != nil {
		return m.Regexp
	}
	return ""
}

func (m *Config) GetURLTemplate() string {
	if m != nil {
		return m.URLTemplate
	}
	return ""
}

func (m *Config) GetBodyTemplate() string {
	if m != nil {
		return m.BodyTemplate
	}
	return ""
}

func (m *Config) GetConfirm() bool {
	if m != nil {
		return m.Confirm
	}
	return false
}

func (m *Config) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

type ConfigList struct {
	Config []*Config `protobuf:"bytes,1,rep,name=config" json:"config,omitempty"`
}

func (m *ConfigList) Reset()                    { *m = ConfigList{} }
func (m *ConfigList) String() string            { return proto.CompactTextString(m) }
func (*ConfigList) ProtoMessage()               {}
func (*ConfigList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ConfigList) GetConfig() []*Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type Channels struct {
	List []string `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *Channels) Reset()                    { *m = Channels{} }
func (m *Channels) String() string            { return proto.CompactTextString(m) }
func (*Channels) ProtoMessage()               {}
func (*Channels) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Channels) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type GetChannelsRequest struct {
}

func (m *GetChannelsRequest) Reset()                    { *m = GetChannelsRequest{} }
func (m *GetChannelsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetChannelsRequest) ProtoMessage()               {}
func (*GetChannelsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*GetConfigListRequest)(nil), "firestarter.GetConfigListRequest")
	proto.RegisterType((*SetConfigResponse)(nil), "firestarter.SetConfigResponse")
	proto.RegisterType((*DeleteConfigRequest)(nil), "firestarter.DeleteConfigRequest")
	proto.RegisterType((*DeleteConfigResponse)(nil), "firestarter.DeleteConfigResponse")
	proto.RegisterType((*Config)(nil), "firestarter.Config")
	proto.RegisterType((*ConfigList)(nil), "firestarter.ConfigList")
	proto.RegisterType((*Channels)(nil), "firestarter.Channels")
	proto.RegisterType((*GetChannelsRequest)(nil), "firestarter.GetChannelsRequest")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x4d, 0x6f, 0x9b, 0x40,
	0x10, 0x35, 0xfe, 0xe0, 0x63, 0xa0, 0x87, 0x8e, 0xdd, 0x74, 0xc5, 0xc1, 0x25, 0x7b, 0x42, 0xaa,
	0xe4, 0x43, 0xaa, 0x1e, 0x7a, 0x6c, 0x1c, 0x29, 0x8a, 0x94, 0xd3, 0xc6, 0xf9, 0x01, 0x98, 0x4e,
	0x52, 0x54, 0x02, 0x94, 0xdd, 0x54, 0xee, 0xad, 0xbf, 0xac, 0xbf, 0xad, 0x62, 0xd9, 0x60, 0x88,
	0x51, 0x6f, 0xcc, 0x9b, 0x37, 0x6f, 0xe7, 0xe3, 0x01, 0x41, 0x5a, 0x16, 0x0f, 0xd9, 0xe3, 0xa6,
	0xaa, 0x4b, 0x55, 0xa2, 0xff, 0x90, 0xd5, 0x24, 0x55, 0x52, 0x2b, 0xaa, 0xf9, 0x19, 0xac, 0xae,
	0x49, 0x6d, 0x75, 0xfe, 0x36, 0x93, 0x4a, 0xd0, 0xcf, 0x67, 0x92, 0x8a, 0x2f, 0xe1, 0xed, 0xdd,
	0x0b, 0x2e, 0x48, 0x56, 0x65, 0x21, 0x89, 0x7f, 0x86, 0xe5, 0x15, 0xe5, 0xa4, 0xe8, 0x05, 0xd7,
	0x5c, 0x5c, 0x03, 0x6c, 0x93, 0x3c, 0xdf, 0x27, 0xe9, 0x8f, 0x9b, 0x2b, 0x66, 0x45, 0x56, 0xec,
	0x09, 0x48, 0x3b, 0xa4, 0x79, 0x63, 0x58, 0x66, 0xe4, 0xfe, 0x4c, 0xc1, 0x6e, 0x21, 0x5c, 0xc1,
	0x62, 0x97, 0xa9, 0x9c, 0x4c, 0xf5, 0x42, 0x35, 0xc1, 0x2b, 0xe1, 0xe9, 0x6b, 0x61, 0x0c, 0xc1,
	0xdd, 0x7e, 0x4f, 0x8a, 0x82, 0x72, 0xc9, 0x66, 0xd1, 0x2c, 0xf6, 0x84, 0x9b, 0x9a, 0x18, 0x11,
	0xe6, 0x3b, 0x3a, 0x28, 0x36, 0xd7, 0x55, 0x73, 0x45, 0x07, 0x85, 0x67, 0x60, 0x0b, 0x7a, 0xa4,
	0x43, 0xc5, 0x16, 0x1a, 0xb5, 0x6b, 0x1d, 0x61, 0x04, 0xfe, 0xbd, 0xb8, 0xdd, 0xd1, 0x53, 0x95,
	0x27, 0x8a, 0x98, 0xad, 0x93, 0xfe, 0xf3, 0x11, 0x42, 0x0e, 0xc1, 0x65, 0xf9, 0xed, 0x77, 0x47,
	0x71, 0x34, 0x25, 0xd8, 0xf7, 0x30, 0x64, 0xe0, 0xe8, 0x69, 0xea, 0x27, 0xe6, 0x46, 0x56, 0xec,
	0x0a, 0x27, 0x6d, 0xc3, 0x26, 0xf3, 0x35, 0x55, 0x59, 0x59, 0x48, 0xe6, 0xe9, 0x36, 0x9d, 0xa4,
	0x0d, 0xf9, 0x17, 0x80, 0xe3, 0xee, 0xf1, 0x23, 0xd8, 0xed, 0xa5, 0x98, 0x15, 0xcd, 0x62, 0xff,
	0x62, 0xb9, 0xe9, 0x9d, 0x6a, 0x63, 0xb6, 0x67, 0x28, 0x7c, 0x7d, 0x1c, 0xbe, 0x19, 0x36, 0xcf,
	0xa4, 0xd2, 0x65, 0x9e, 0xd0, 0xdf, 0x7c, 0x05, 0xd8, 0x5c, 0xd6, 0x50, 0xcc, 0xad, 0x2e, 0xfe,
	0x4e, 0xe1, 0x4d, 0x2b, 0x74, 0x47, 0xf5, 0xaf, 0x2c, 0x25, 0xbc, 0x01, 0xaf, 0x73, 0x00, 0x9e,
	0x0f, 0x5e, 0x1c, 0x73, 0x46, 0xf8, 0x7e, 0xa4, 0xa9, 0x26, 0xcf, 0x27, 0x78, 0x09, 0x5e, 0x67,
	0x1a, 0x1c, 0x6b, 0x3e, 0x5c, 0x0f, 0xc0, 0x53, 0x87, 0x4d, 0xf0, 0x1e, 0x82, 0xbe, 0x59, 0x30,
	0x1a, 0x54, 0x8c, 0xd8, 0x2f, 0x3c, 0xff, 0x0f, 0xa3, 0x93, 0xbd, 0x06, 0xbf, 0xb7, 0x0d, 0xfc,
	0x70, 0x32, 0xe7, 0x70, 0x4f, 0xe1, 0xbb, 0x61, 0xf7, 0x26, 0xcb, 0x27, 0x7b, 0x5b, 0xff, 0x44,
	0x9f, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x58, 0xf6, 0x8d, 0x54, 0x03, 0x00, 0x00,
}
